"""Another migrate

Revision ID: 79ced98d3eff
Revises: 1873cf506448
Create Date: 2026-07-03 18:18:22.829347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ced98d3eff'
down_revision = '1873cf506448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_feedback')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('writer_public_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('writer_username', sa.String(length=20), nullable=False))
        batch_op.drop_column('writer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer', sa.INTEGER(), nullable=False))
        batch_op.drop_column('writer_username')
        batch_op.drop_column('writer_public_id')
        batch_op.drop_column('writer_id')

    op.create_table('_alembic_tmp_feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('writer_id', sa.INTEGER(), nullable=False),
    sa.Column('writer_public_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('writer_username', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('writer_public_id', name=op.f('uq_feedback_writer_public_id')),
    sa.UniqueConstraint('writer_username', name=op.f('uq_feedback_writer_username'))
    )
    # ### end Alembic commands ###
